name: wedding-honeymoon-docker
services:
- name: web
  image:
    registry_type: DOCR
    registry: apex-workout
    repository: wedding-honeymoon
    tag: latest
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 80
  routes:
  - path: /
  health_check:
    http_path: /
